_wandb:
    value:
        cli_version: 0.24.0
        e:
            ok1cxfln5cw4d3f7zaau7ewcjn9lmrw6:
                args:
                    - --config-path
                    - /hpc2hdd/home/mpeng885/wyy/NPG_Muse/verl/recipe/NPG-Muse/sft
                    - --config-name
                    - sft_trainer_qwen25_1m.yaml
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "844362571776"
                        used: "285155835904"
                email: 1377143236@qq.com
                executable: /hpc2hdd/home/mpeng885/jerryjiawenl/henansun/anaconda3/envs/verl-0.5.0/bin/python
                gpu: NVIDIA A800-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-3930cbda-db8f-3c3b-37eb-3f64c0ade744
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-60ca5b75-5cd9-76bb-93f1-85c1566aa6c2
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-0dbbbbfb-681f-30d1-4e5d-4f858eb33b74
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-aace9536-5fdb-b13f-801a-b0169f4f8933
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-38dce28e-b41c-0ded-5259-73ff1d925291
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-c98e8def-06c2-b7da-648f-6bd7c9081f2c
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-e9e1c5fd-302b-7b67-17d3-7742d20b8fbd
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-ec102c54-b6ee-21d2-39bc-a725fc58d98f
                host: 1b5f6259595f
                memory:
                    total: "1081840775168"
                os: Linux-5.4.0-165-generic-x86_64-with-glibc2.35
                program: -m verl.trainer.fsdp_sft_trainer
                python: CPython 3.10.19
                root: /hpc2hdd/home/mpeng885/wyy/NPG_Muse/verl
                startedAt: "2026-01-21T09:34:11.514602Z"
                writerId: ok1cxfln5cw4d3f7zaau7ewcjn9lmrw6
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 98
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 98
                - 105
            "3":
                - 2
                - 13
                - 61
            "4": 3.10.19
            "5": 0.24.0
            "6": 4.51.1
            "8":
                - 2
            "12": 0.24.0
            "13": linux-x86_64
