_wandb:
    value:
        cli_version: 0.24.0
        e:
            yc9qrzrn9819dfjvl28sf88twpt7gsf7:
                args:
                    - --config-path
                    - /hpc2hdd/home/mpeng885/wyy/NPG_Muse/verl/recipe/NPG-Muse/sft
                    - --config-name
                    - sft_trainer_qwen3_3np.yaml
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "844362571776"
                        used: "413561479168"
                email: 1377143236@qq.com
                executable: /hpc2hdd/home/mpeng885/jerryjiawenl/henansun/anaconda3/envs/verl-0.5.0/bin/python
                gpu: NVIDIA A800-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-1b9dc668-af54-1bde-cb7a-2c653bfeefc2
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-63de14f8-d6a3-0038-3751-4136a13e585d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-9d12b324-9004-f5e5-c681-6e239ca1e566
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-04f7d337-26b4-ace9-6cc9-25c591917347
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-5dd79220-7190-2bb2-5b68-1c6df7a8d42d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-0bbae911-c409-921a-0c4a-95c879575602
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-7def2208-8c97-2a0b-87d4-71aa5751d327
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-e071fda3-d580-8a2d-27af-153697d44aba
                host: e4d660fc861d
                memory:
                    total: "1081840553984"
                os: Linux-5.4.0-155-generic-x86_64-with-glibc2.35
                program: -m verl.trainer.fsdp_sft_trainer
                python: CPython 3.10.19
                root: /hpc2hdd/home/mpeng885/wyy/NPG_Muse/verl/recipe/NPG-Muse
                startedAt: "2026-01-21T14:34:57.477624Z"
                writerId: yc9qrzrn9819dfjvl28sf88twpt7gsf7
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 98
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 98
                - 105
            "3":
                - 2
                - 13
                - 61
            "4": 3.10.19
            "5": 0.24.0
            "6": 4.51.1
            "8":
                - 2
            "12": 0.24.0
            "13": linux-x86_64
